spring:
  datasource:
    url: jdbc:mysql:xxxxxxxxxxxxxxxxx;
    username: root
    password: xxxxxxxxxxxxxxxx;
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.yangtongxue.springboot.*
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  jdbc:
    template:
      query-timeout: 3
